---
title: "vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tornadodecimatestrailerpark)
```

```{r}
data("hurdat")
head(data)
```
```{r}
#1.
storm_2020 <- data[substr(data$date, start = 1, stop = 4) == "2020", "id"]
storm_ids_2020=unique(storm_2020)
print(storm_ids_2020)
plot_storm_tracks(data, storm_ids_2020)
for (storm_id in storm_ids_2020) {
    # Subset the data for the current storm
    storm_start <- data[which(data$id == storm_id)[1], ]
    lat=storm_start$latitude
    long=storm_start$longitude
    name=storm_start$name
    text(long,lat,name,cex=0.25)
}
title("Tracks of storms in 2020")
storm_2021 <- data[substr(data$date, start = 1, stop = 4) == "2021", "id"]
storm_ids_2021=unique(storm_2021)
plot_storm_tracks(data, storm_ids_2021)
for (storm_id in storm_ids_2021) {
    # Subset the data for the current storm
    storm_start <- data[which(data$id == storm_id)[1], ]
    lat=storm_start$latitude
    long=storm_start$longitude
    name=storm_start$name
    text(long,lat,name,cex=0.25)
}
title("Tracks of storms in 2021")
storm_2022 <- data[substr(data$date, start = 1, stop = 4) == "2022", "id"]
storm_ids_2022=unique(storm_2022)
plot_storm_tracks(data, storm_ids_2022)
for (storm_id in storm_ids_2022) {
    # Subset the data for the current storm
    storm_start <- data[which(data$id == storm_id)[1], ]
    lat=storm_start$latitude
    long=storm_start$longitude
    name=storm_start$name
    text(long,lat,name,cex=0.25)
}
title("Tracks of storms in 2022")
```
```{r}
#2.
us_map <- maps::map("state", plot = FALSE)
us_boundary <- data.frame(x = us_map$x, y = us_map$y)
names=c("KATRINA","SANDY","HARVEY","IAN")
index_lst=NULL
for (name in names){
  storm_subset_katrina <- data[grepl(name, data$name), ]
  landfall_katrina=NULL
  for (i in 1:nrow(storm_subset_katrina)) {
    latitude <- storm_subset_katrina$latitude[i]
    longitude <- storm_subset_katrina$longitude[i]
    in_us <- sp::point.in.polygon(point.x = longitude, point.y = latitude, pol.x = us_boundary$x, pol.y = us_boundary$y)
    landfall_katrina=c(landfall_katrina,in_us)
  }
  fall=storm_subset_katrina[which(landfall_katrina==1),]
  fall_m=fall[is.na(fall$`34_wind_radii_northeastern`)==F,]
  index=as.numeric(rownames(fall_m[which(fall_m$max_wind==max(fall_m$max_wind)),]))
  index2=which(as.numeric(rownames(data))==tail(index,1))
  index_lst=c(index_lst,index2)
}
plot_storm_size(data,index_lst[1])
plot_storm_size(data,index_lst[2])
plot_storm_size(data,index_lst[3])
plot_storm_size(data,index_lst[4])
```

```{r}
#3.
unique_storm_ids <- unique(data$id)
new_data <- data.frame()
for (storm_id in unique_storm_ids) {
    storm_subset <- data[data$id == storm_id, ]
    name=unique(storm_subset$name)
    max=max(storm_subset$max_wind)
    min=min(storm_subset$min_pressure)
    ace=ace_of_storm(data,storm_id)
    landfall=storm_US_landfall(data,storm_id)
    new_data=rbind(new_data,c(storm_id,name,max,min,landfall,ace))
}
colnames(new_data)=c("storm id","storm_name","maximum wind speed","minimum pressure","indicator for landfall","accumulated cyclone energy")
```

```{r}
#4.(a)
years=c("2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022")
ace_lst=NULL
for (year in years){
  storm_2020 <-data[substr(data$date, start = 1, stop = 4) == year,]
  storm_ids_2020=unique(storm_2020$id)
  cum=0
  for (storm_id in storm_ids_2020) {
      cum=cum+ace_of_storm(storm_2020,storm_id)
  }
  ace_lst=c(ace_lst,cum)
}
plot(x=years, y=ace_lst)
title("ACE vs Year (Latest 10 Years)")
#4.(b)
months=c("01","02","03","04","05","06","07","08","09","10","11","12")
ace_lst=NULL
data_after_2012=data[48081:nrow(data),]
for (month in months){
  storm_2020 <-data_after_2012[substr(data_after_2012$date, start = 5, stop = 6) == month,]
  storm_ids_2020=unique(storm_2020$id)
  cum=0
  for (storm_id in storm_ids_2020) {
      cum=cum+ace_of_storm(storm_2020,storm_id)
  }
  ace_lst=c(ace_lst,cum)
}
plot(x=months, y=ace_lst,ylim=c(0,500))
title("ACE vs Month (Latest 10 Years)")
```

```{r}
#5.
# unique storm ids
unique_storm_data <- data[!duplicated(data$id),]
# Assuming storm_data is already loaded and storm_US_landfall() function is defined
unique_storm_data$us_landfall <- sapply(unique_storm_data$id, storm_US_landfall,storm_data = data)
# get the year of each storm
unique_storm_data$unique_year <- as.numeric(substr(unique_storm_data$date, 1, 4))
# aggregate the number of landfalls per year
landfall_per_year <- aggregate(us_landfall ~ unique_year, data=unique_storm_data,sum)
# train a linear model
model <- lm(us_landfall ~ unique_year, data = landfall_per_year)
summary(model)

# I define a landfalling hurricane as one that makes landfall in the continental United States.
# I set the time period to be one year. If a hurricane that makes landfall in the US exists for more than one year, it counts for the first year.
# No matter how many times a hurricane makes landfall in the US, it is counted as one landfalling hurricane as long as its id is the same.
# I use a linear model to fit the number of landfalling hurricanes per year. The model is: number of landfalling hurricanes = b0 + b1 * year, where b0 is the intercept, and b1 is the coefficient of the year variable.
# The estimated coefficient of year is 0.010311 with a p-value of 0.000465. Although it is small, its p-value is statistically significant (p < 0.05). So the number of landfalling hurricanes is increasing over time.
```

```{r}
#6.
# only data with status=HU/TS/TD
tropical_cyclones <- data[grepl("HU|TS|TD", data$status), ]
unique_tropical_cyclones_data <- tropical_cyclones[!duplicated(tropical_cyclones$id),]
ace_per_storm <- sapply(unique_tropical_cyclones_data$id, function(id) ace_of_storm(tropical_cyclones, id))
unique_year <- as.numeric(substr(unique_tropical_cyclones_data$date, 1, 4))


# Combine storm years and ACEs into a data frame
yearly_ace_data <- data.frame(year = unique_year, ace = ace_per_storm)

# Sum ACEs per year
yearly_ace_sum <- aggregate(ace ~ year, data = yearly_ace_data, sum)
# train a linear model
model <- lm(ace ~ year, data = yearly_ace_sum)
summary(model)

# I define a tropical cyclone has a status of HU/TS/TD. I define intensity to be the sum of accumulated cyclone energy.
# I set the time period to be one year. If a hurricane exists for more than one year, it counts for the first year.
# I use a linear model to fit sum of accumulated cyclone energy per year. The model is: accumulated cyclone energy = b0 + b1 * year, where b0 is the intercept, and b1 is the coefficient of the year variable.
# The estimated coefficient of year is 0.39219 with a p-value of 3.66e-06. Its p-value is statistically significant (p < 0.05), so the intensity of tropical cyclones is increasing over time.

```

